In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

# Ejercicio 1
Descarga el fecha siete Airlines Delay: Airline on-time statistics and delay causas y cárgalo en un Pandas Dataframe. Explora los datos que contiene, explica brevemente qué variables existen y queda únicamente con las columnas que consideres relevantes. Justifica tu elección.

In [3]:
vuelosalpha = pd.read_csv("DelayedFlights.csv")

In [4]:
pd.set_option('display.max_columns',500)
vuelosalpha

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,N712SW,128.0,150.0,116.0,-14.0,8.0,IAD,TPA,810,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,N772SW,128.0,145.0,113.0,2.0,19.0,IAD,TPA,810,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,448,N428WN,96.0,90.0,76.0,14.0,8.0,IND,BWI,515,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,90.0,90.0,77.0,34.0,34.0,IND,BWI,515,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,N726SW,101.0,115.0,87.0,11.0,25.0,IND,JAX,688,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,7009710,2008,12,13,6,1250.0,1220,1617.0,1552,DL,1621,N938DL,147.0,152.0,120.0,25.0,30.0,MSP,ATL,906,9.0,18.0,0,N,0,3.0,0.0,0.0,0.0,22.0
1936754,7009717,2008,12,13,6,657.0,600,904.0,749,DL,1631,N3743H,127.0,109.0,78.0,75.0,57.0,RIC,ATL,481,15.0,34.0,0,N,0,0.0,57.0,18.0,0.0,0.0
1936755,7009718,2008,12,13,6,1007.0,847,1149.0,1010,DL,1631,N909DA,162.0,143.0,122.0,99.0,80.0,ATL,IAH,689,8.0,32.0,0,N,0,1.0,0.0,19.0,0.0,79.0
1936756,7009726,2008,12,13,6,1251.0,1240,1446.0,1437,DL,1639,N646DL,115.0,117.0,89.0,9.0,11.0,IAD,ATL,533,13.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1936757,7009727,2008,12,13,6,1110.0,1103,1413.0,1418,DL,1641,N908DL,123.0,135.0,104.0,-5.0,7.0,SAT,ATL,874,8.0,11.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [5]:
Total_delay = vuelosalpha['WeatherDelay'] + vuelosalpha['ArrDelay'] + vuelosalpha['CarrierDelay'] + vuelosalpha['DepDelay'] + vuelosalpha['LateAircraftDelay'] + vuelosalpha['NASDelay'] + vuelosalpha['SecurityDelay']

In [6]:
Total_delay

0            NaN
1            NaN
2            NaN
3          102.0
4            NaN
           ...
1936753     80.0
1936754    207.0
1936755    278.0
1936756      NaN
1936757      NaN
Length: 1936758, dtype: float64

In [7]:
vuelosalpha['Total_delay'] = Total_delay

Aquí sume todos los 'Delay' que existen para sacar el total y en el futuro usar el tiempo del retraso con facilidad en caso de que no nos importe las causas sino el tiempo.

## Nota
Descubri que basicamente ArrDelay es lo mismo pero más exacto (ademas que lo estoy contando por lo que Total_delay es erroneo por que basicamente estamos duplicando el resultado).

In [8]:
vuelosalpha.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
Total_delay          689270
dtype: int64

In [9]:
vuelosalpha['TailNum']

0          N712SW
1          N772SW
2          N428WN
3          N464WN
4          N726SW
            ...
1936753    N938DL
1936754    N3743H
1936755    N909DA
1936756    N646DL
1936757    N908DL
Name: TailNum, Length: 1936758, dtype: object

In [10]:
vuelosalpha['AirTime'].fillna(0, inplace=True)
vuelosalpha['CarrierDelay'].fillna(0, inplace=True)
vuelosalpha['WeatherDelay'].fillna(0, inplace=True)
vuelosalpha['NASDelay'].fillna(0, inplace=True)
vuelosalpha['LateAircraftDelay'].fillna(0, inplace=True)
vuelosalpha['Total_delay'].fillna(0, inplace=True)
vuelosalpha['ArrDelay'].fillna(0, inplace=True)
vuelosalpha['TaxiIn'].fillna(0, inplace=True)
vuelosalpha['TaxiOut'].fillna(0, inplace=True)
vuelosalpha['CRSElapsedTime'].fillna(0, inplace=True)
vuelosalpha['TailNum'].fillna('-', inplace=True)
vuelosalpha['ArrTime'].fillna(0, inplace=True)
vuelosalpha['SecurityDelay'].fillna(0, inplace=True)
vuelosalpha['ActualElapsedTime'].fillna(0, inplace=True)

In [11]:
vuelosalpha.isnull().sum()

Unnamed: 0           0
Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
Cancelled            0
CancellationCode     0
Diverted             0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
Total_delay          0
dtype: int64

Aquí limpiamos el data set para no tener ningún null de por medio cuando hagamos nuestros calculos. Los null en la mayoria de los casos significa que por alguna u otra razon no se registraron sea por  que el vuelo se cancelo, desvio o alguna otra cosa, la mayoria tienen que ver con el tiempo del vuelo, cuanto se retrasaron o similares. Por lo que se transformaron en zeros para facilitar los calculos y porque se puede considerar correcto ese dato ya que tecnicamente no retrasos ni tiempo de vuelos es decir 0. La única excepción fue'TailNum' ya que son números de identificación, por lo que se marco un '-' para mostrar los aviones sin identificar.

In [12]:
vuelos_recortados = vuelosalpha.sample(n=200000, random_state=42)

In [13]:
vuelos_recortados

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Total_delay
1782417,6583804,2008,12,6,6,1805.0,1755,2146.0,2035,YV,7281,N505MJ,281.0,220.0,177.0,71.0,10.0,IAD,AUS,1297,5.0,99.0,0,N,0,71.0,0.0,0.0,0.0,0.0,152.0
512712,1604365,2008,3,23,7,2120.0,1200,2241.0,1333,NW,131,N777NC,81.0,93.0,55.0,548.0,560.0,ORD,MSP,334,7.0,19.0,0,N,0,543.0,0.0,0.0,0.0,5.0,1656.0
447137,1395655,2008,3,31,1,1731.0,1710,1819.0,1810,OO,3676,N224SW,48.0,60.0,44.0,9.0,21.0,SLC,PIH,150,3.0,1.0,0,N,0,0.0,0.0,0.0,0.0,0.0,0.0
55082,178786,2008,1,6,7,1507.0,1413,1601.0,1509,OO,6573,N708SK,54.0,56.0,32.0,52.0,54.0,HDN,DEN,142,5.0,17.0,0,N,0,0.0,0.0,0.0,0.0,52.0,158.0
877634,2972767,2008,5,22,4,637.0,630,812.0,750,CO,1869,N16646,155.0,140.0,134.0,22.0,7.0,JAX,IAH,817,5.0,16.0,0,N,0,0.0,0.0,15.0,7.0,0.0,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106815,3683895,2008,7,26,6,1903.0,1850,1957.0,1945,WN,1610,N614SW,54.0,55.0,42.0,12.0,13.0,SAT,DAL,248,5.0,7.0,0,N,0,0.0,0.0,0.0,0.0,0.0,0.0
269784,858235,2008,2,9,6,1834.0,1810,2009.0,1953,US,1753,N188US,95.0,103.0,85.0,16.0,24.0,CLT,TPA,508,3.0,7.0,0,N,0,16.0,0.0,0.0,0.0,0.0,56.0
627539,2001715,2008,4,16,3,1633.0,1626,1750.0,1745,OO,6410,N418SW,77.0,79.0,56.0,5.0,7.0,BUR,SFO,326,4.0,17.0,0,N,0,0.0,0.0,0.0,0.0,0.0,0.0
292264,931040,2008,2,24,7,2137.0,2130,2337.0,2340,EV,4912,N741EV,120.0,130.0,99.0,-3.0,7.0,ATL,SYR,793,5.0,16.0,0,N,0,0.0,0.0,0.0,0.0,0.0,0.0
554861,1737123,2008,3,23,7,1848.0,1630,2148.0,1935,B6,1203,N192JB,180.0,185.0,163.0,133.0,138.0,BUF,RSW,1144,5.0,12.0,0,N,0,15.0,0.0,0.0,0.0,118.0,404.0

Aquí tomo una muestra la muestra de 200,000

In [14]:
datos_relevantes = ['Month', 'Distance', 'AirTime', 'Origin', 'Dest', 'CancellationCode', 'Diverted', 'ArrDelay']

In [15]:
set(vuelosalpha['Year'])

{2008}

In [16]:
vueloscancelados = vuelosalpha['Cancelled'] == 0

In [17]:
vuelosN = vuelosalpha['CancellationCode'] == 'N'

In [18]:
target = vuelosN == vueloscancelados

In [19]:
len(target) - target.count()

0

### Los datos escojidos

En 'datos_relevantes' escojo las columnas, aunque las razones las explico abajo: 
1. Excluyo año porque todos ocurren en 2008 y no hay otro año así que me quede con el Mes porque los demas me parecen demasiado especifico.
2. Hice un codigo para verificar si N considia siempre con 0 (Equivalencia a que no se cancelo) y viceversa, podemos confirmar que siempre coinciden por lo que incluir ambas es redundar y CancellationCode incluye información adicional por lo que le di prioridad.
3. Escoji ArrDelay en lugar de Total_Delay porque ArrDelay es lo mismo pero más exacto (ademas que lo estoy contando por lo que Total_delay es erroneo por que basicamente estamos duplicando el resultado).
4. Origin y Dest los escoji porque me parecen información basica.
5. CancellationCode y Diverted porque son anomalias importantes en mi opinión.

In [20]:
vuelos = vuelos_recortados[datos_relevantes]

In [21]:
vuelos

,Month,Distance,AirTime,Origin,Dest,CancellationCode,Diverted,ArrDelay
1782417,12,1297,177.0,IAD,AUS,N,0,71.0
512712,3,334,55.0,ORD,MSP,N,0,548.0
447137,3,150,44.0,SLC,PIH,N,0,9.0
55082,1,142,32.0,HDN,DEN,N,0,52.0
877634,5,817,134.0,JAX,IAH,N,0,22.0
...,...,...,...,...,...,...,...,...
1106815,7,248,42.0,SAT,DAL,N,0,12.0
269784,2,508,85.0,CLT,TPA,N,0,16.0
627539,4,326,56.0,BUR,SFO,N,0,5.0
292264,2,793,99.0,ATL,SYR,N,0,-3.0
554861,3,1144,163.0,BUF,RSW,N,0,133.0

# Ejercicio 2
Realiza un informe completo del dataset:

1. Resume estadísticamente el dataset y las columnas de interés. Haz un análisis estadístico de lo que consideres relevante.
2. Encuentra cuántos datos faltantes hay por columna.
3. Crea nuevas columnas (velocidad media del vuelo, si ha llegado tarde o no...).
4. Haz una mesa de las aerolíneas con mayores retrasos acumulados.
5. ¿Cuáles son los vuelos más largos? ¿Y los más atrasados? Busca las rutas más largas y las que acumulen más retrasos.
       Aporta lo que consideres relevante.

Abajo vemos el resumen de las estadisticas y a continuación comparto mis conclusiones. 
###### Month 
Lo único que puedo concluir es que de los datos que poseemos la ligera mayoria son de la segunda mitad del año.
###### Distance
Hay dos cosas que me llaman la atención en esta variable, Min: Me sorprendio la poca distancia del vuelo más corto, supongo que serán vuelos de estados muy cercanos y Std: que muestra que la distancia de los vuelos son significativamente diferente aunque tampoco es algo que yo concideraria como variaciones demasiado altas.
###### AirTime
Probablemente lo más notorio es que min es 0 cuando existen nulls en esta variables, lo que no me explico. 
###### Diverted
Lo único a considerar es que (naturalmente) hay muchos menos desvios que no desvios
###### ArrDelay
Lo más notable es la existencia de números negativos que supongo que se supone a la existencia de vuelos que llegaron temprano.

In [22]:
vuelos.describe()

,Month,Distance,AirTime,Diverted,ArrDelay
count,200000.000000,200000.00000,200000.000000,200000.000000,200000.000000
mean,6.106975,764.96174,107.724790,0.004065,42.186505
std,3.476865,572.85671,68.694157,0.063628,56.948641
min,1.000000,11.00000,0.000000,0.000000,-57.000000
25%,3.000000,340.00000,58.000000,0.000000,9.000000
50%,6.000000,607.00000,90.000000,0.000000,24.000000
75%,9.000000,998.00000,137.000000,0.000000,56.000000
max,12.000000,4962.00000,644.000000,1.000000,2453.000000

## Datos faltantes hay por columna

In [23]:
vuelos.isnull().sum()

Month               0
Distance            0
AirTime             0
Origin              0
Dest                0
CancellationCode    0
Diverted            0
ArrDelay            0
dtype: int64

Podemos ver que no existen nulls porque ya fueron limpiados antes

## Crear nuevas columnas

In [24]:
vuelos['VelocidadMedia'] = (vuelos['Distance'] / (vuelos['AirTime']/60))

D:\users\ciberintegra_14\AppData\Local\Temp\ipykernel_2784\1487713365.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vuelos['VelocidadMedia'] = (vuelos['Distance'] / (vuelos['AirTime']/60))

In [25]:
vuelos['VelocidadMedia']

1782417    439.661017
512712     364.363636
447137     204.545455
55082      266.250000
877634     365.820896
              ...
1106815    354.285714
269784     358.588235
627539     349.285714
292264     480.606061
554861     421.104294
Name: VelocidadMedia, Length: 200000, dtype: float64

In [26]:
vuelos['VelocidadMedia'].fillna(0, inplace=True)

D:\users\ciberintegra_14\AppData\Local\Temp\ipykernel_2784\2447861608.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vuelos['VelocidadMedia'].fillna(0, inplace=True)

In [27]:
vuelos['VelocidadMedia'].isnull().sum()

0

Aquí creo la columna VelicidadMedia utilizando la formula 'distancia total / tiempo total' usando Distance y AirTime respectivamente. Ya que no estoy seguro de las unidades (especialmente de Distance) no las coloco.

In [28]:
def etiquetar_retraso(Arr_Delay):
    if Arr_Delay <= 15:
        return 0
    else:
        return 1

In [29]:
Retraso = vuelos['ArrDelay'].apply(etiquetar_retraso)

In [30]:
Retraso

1782417    1
512712     1
447137     0
55082      1
877634     1
          ..
1106815    0
269784     1
627539     0
292264     0
554861     1
Name: ArrDelay, Length: 200000, dtype: int64

In [31]:
vuelos['Retraso'] = Retraso

D:\users\ciberintegra_14\AppData\Local\Temp\ipykernel_2784\813572571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vuelos['Retraso'] = Retraso

Realizo una función para determinar si los vuelos se retrasaron.
## Nota Aclaratria:
En la tabla no se cuenta como retraso en las otras columnas a menos que ArrDelay sea mayor a 15.

In [32]:
vuelos

,Month,Distance,AirTime,Origin,Dest,CancellationCode,Diverted,ArrDelay,VelocidadMedia,Retraso
1782417,12,1297,177.0,IAD,AUS,N,0,71.0,439.661017,1
512712,3,334,55.0,ORD,MSP,N,0,548.0,364.363636,1
447137,3,150,44.0,SLC,PIH,N,0,9.0,204.545455,0
55082,1,142,32.0,HDN,DEN,N,0,52.0,266.250000,1
877634,5,817,134.0,JAX,IAH,N,0,22.0,365.820896,1
...,...,...,...,...,...,...,...,...,...,...
1106815,7,248,42.0,SAT,DAL,N,0,12.0,354.285714,0
269784,2,508,85.0,CLT,TPA,N,0,16.0,358.588235,1
627539,4,326,56.0,BUR,SFO,N,0,5.0,349.285714,0
292264,2,793,99.0,ATL,SYR,N,0,-3.0,480.606061,0
554861,3,1144,163.0,BUF,RSW,N,0,133.0,421.104294,1

## Mesa de las aerolíneas con mayores retrasos acumulados

In [33]:
vuelos['UniqueCarrier'] = vuelosalpha['UniqueCarrier']

D:\users\ciberintegra_14\AppData\Local\Temp\ipykernel_2784\789266301.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vuelos['UniqueCarrier'] = vuelosalpha['UniqueCarrier']

Para realizar este ejercicio tuve que añadir esta columna porque estos datos son necesarios para encontar lo que buscamos.

In [34]:
vuelos

,Month,Distance,AirTime,Origin,Dest,CancellationCode,Diverted,ArrDelay,VelocidadMedia,Retraso,UniqueCarrier
1782417,12,1297,177.0,IAD,AUS,N,0,71.0,439.661017,1,YV
512712,3,334,55.0,ORD,MSP,N,0,548.0,364.363636,1,NW
447137,3,150,44.0,SLC,PIH,N,0,9.0,204.545455,0,OO
55082,1,142,32.0,HDN,DEN,N,0,52.0,266.250000,1,OO
877634,5,817,134.0,JAX,IAH,N,0,22.0,365.820896,1,CO
...,...,...,...,...,...,...,...,...,...,...,...
1106815,7,248,42.0,SAT,DAL,N,0,12.0,354.285714,0,WN
269784,2,508,85.0,CLT,TPA,N,0,16.0,358.588235,1,US
627539,4,326,56.0,BUR,SFO,N,0,5.0,349.285714,0,OO
292264,2,793,99.0,ATL,SYR,N,0,-3.0,480.606061,0,EV
554861,3,1144,163.0,BUF,RSW,N,0,133.0,421.104294,1,B6

In [35]:
(vuelos.groupby('UniqueCarrier')['Retraso'].sum()).sort_values(ascending=False)

UniqueCarrier
WN    20334
AA    13337
MQ     9852
UA     9657
OO     8991
XE     7327
DL     7272
US     6044
CO     6041
EV     5786
NW     5414
YV     5137
FL     4723
B6     3885
OH     3867
9E     3491
AS     2384
F9     1622
HA      429
AQ       32
Name: Retraso, dtype: int64

Para poder realizar esta operanción tuve que añadir 'UniqueCarrier' donde se muestran a las distintas compañias. Luego para encontrar tuvo la mayor cantidad de retrasos acumulados los agrupe con Retraso y despues utilize sum aprovechando que fueron organizados con zeros y unos, finalmente los ordene descendentemente.

## Vuelos más atrasados y más largos

In [36]:
vuelos.nlargest(10, 'ArrDelay')

,Month,Distance,AirTime,Origin,Dest,CancellationCode,Diverted,ArrDelay,VelocidadMedia,Retraso,UniqueCarrier
686014,4,930,132.0,CLT,MSP,N,0,2453.0,422.727273,1,NW
685437,4,449,63.0,MOT,MSP,N,0,1542.0,427.619048,1,NW
521096,3,200,47.0,BNA,MEM,N,0,1490.0,255.319149,1,NW
1400101,8,988,124.0,SLC,DFW,N,0,1286.0,478.064516,1,AA
1502764,9,813,112.0,TUS,DFW,N,0,1186.0,435.535714,1,AA
1193616,7,665,88.0,PHL,ATL,N,0,1175.0,453.409091,1,FL
1213016,7,1307,171.0,TPA,MSP,N,0,1158.0,458.596491,1,NW
66969,1,2486,301.0,LAX,OGG,N,0,1081.0,495.548173,1,UA
1021378,6,812,121.0,MSN,LGA,N,0,1057.0,402.644628,1,MQ
1898129,12,813,104.0,TUS,DFW,N,0,1049.0,469.038462,1,AA

In [37]:
vuelos.nlargest(10, 'Distance')

,Month,Distance,AirTime,Origin,Dest,CancellationCode,Diverted,ArrDelay,VelocidadMedia,Retraso,UniqueCarrier
1620205,10,4962,588.0,EWR,HNL,N,0,-3.0,506.326531,0,CO
365249,2,4962,637.0,EWR,HNL,N,0,39.0,467.378336,1,CO
1727415,11,4962,622.0,EWR,HNL,N,0,5.0,478.649518,0,CO
1414094,8,4962,546.0,HNL,EWR,N,0,27.0,545.274725,1,CO
1255336,7,4962,610.0,EWR,HNL,N,0,21.0,488.065574,1,CO
1620824,10,4962,544.0,HNL,EWR,N,0,15.0,547.279412,0,CO
368631,2,4962,537.0,HNL,EWR,N,0,9.0,554.413408,0,CO
556361,3,4962,527.0,HNL,EWR,N,0,-5.0,564.933586,0,CO
1922433,12,4962,613.0,EWR,HNL,N,0,-12.0,485.676998,0,CO
1927699,12,4962,531.0,HNL,EWR,N,0,65.0,560.677966,1,CO

Aquí se muestran los diez vuelos más atrasados y más largos, respectivamente, algo interesante es que los diez vuelos más largos de nuestra muestra pertenecen a la misma compañia 'CO'. El vuelo más atrasado es de CLT a MSP y los vuelos más largos fueron entre EWR y HNL

# Ejercicio 3
Exporta el dataset limpio y con las nuevas columnas a Excel.

In [38]:
vuelos.to_excel("Vuelos.xlsx", index=False)

Subo el archivo al Github